In [13]:
import pandas as pd
import numpy as np
from pathlib import Path

print("ShopSphere Data Cleaning & ETL")
print("=" * 50)

ShopSphere Data Cleaning & ETL
==================================================

In [14]:
RAW_PATH = Path("../02_Raw_Data")
CLEAN_PATH = Path("../04_Python_ETL/cleaned_data")

CLEAN_PATH.mkdir(parents=True, exist_ok=True)

print("Raw data:", RAW_PATH.resolve())
print("Clean data:", CLEAN_PATH.resolve())

Raw data: C:\Users\USER\OneDrive\Desktop\ShopSphere-Ecommerce-Analytics\02_Raw_Data
Clean data: C:\Users\USER\OneDrive\Desktop\ShopSphere-Ecommerce-Analytics\04_Python_ETL\cleaned_data

In [15]:
customers = pd.read_csv(RAW_PATH / "customers_raw.csv")
products = pd.read_csv(RAW_PATH / "products_raw.csv")
orders = pd.read_csv(RAW_PATH / "orders_raw.csv")
order_items = pd.read_csv(RAW_PATH / "order_items_raw.csv")
payments = pd.read_csv(RAW_PATH / "payments_raw.csv")
returns = pd.read_csv(RAW_PATH / "returns_raw.csv")
marketing = pd.read_csv(RAW_PATH / "marketing_campaigns_raw.csv")

In [16]:
duplicate_customers = customers[
    customers["customer_id"].duplicated(keep=False)
].sort_values("customer_id")

duplicate_customers

,customer_id,customer_name,gender,date_of_birth,signup_date,acquisition_channel,state,city,customer_segment,email_opt_in,loyalty_member
3510,C103510,Dev Joseph,Male,1968-01-29,2025-05-12,Referral,Rajasthan,Jodhpur,Standard,Yes,Yes
40015,C103510,Dev Joseph,Male,1968-01-29,2025-05-12,Referral,Rajasthan,Jodhpur,Standard,Yes,Yes
5128,C105128,Aisha Iyer,Female,1991-01-10,2022-07-11,Paid Search,Delhi,Delhi,Standard,Yes,No
40012,C105128,Aisha Iyer,Female,1991-01-10,2022-07-11,Paid Search,Delhi,Delhi,Standard,Yes,No
6689,C106689,Pooja Thomas,Male,1987-07-23,2025-05-06,Social Media,Punjab,Amritsar,Standard,Yes,Yes
40003,C106689,Pooja Thomas,Male,1987-07-23,2025-05-06,Social Media,Punjab,Amritsar,Standard,Yes,Yes
9125,C109125,Pooja Patel,Female,1965-12-06,2022-06-14,Email,Bihar,Muzaffarpur,Standard,Yes,Yes
40013,C109125,Pooja Patel,Female,1965-12-06,2022-06-14,Email,Bihar,Muzaffarpur,Standard,Yes,Yes
10919,C110919,Arun Reddy,Female,1993-10-21,2023-12-18,Organic Search,Tamil Nadu,Madurai,Premium,No,Yes
40021,C110919,Arun Reddy,Female,1993-10-21,2023-12-18,Organic Search,Tamil Nadu,Madurai,Premium,No,Yes
40006,C112335,Rohan Thomas,Female,1965-10-29,2022-05-01,Organic Search,Kerala,Thrissur,Standard,Yes,Yes
12335,C112335,Rohan Thomas,Female,1965-10-29,2022-05-01,Organic Search,Kerala,Thrissur,Standard,Yes,Yes
12701,C112701,Nikhil Reddy,Male,1966-03-12,2022-11-17,Social Media,West Bengal,Durgapur,Standard,No,No
40024,C112701,Nikhil Reddy,Male,1966-03-12,2022-11-17,Social Media,West Bengal,Durgapur,Standard,No,No
40011,C113787,Kiran Jain,Male,1976-11-26,2024-02-23,Paid Search,Tamil Nadu,Tiruchirappalli,Standard,Yes,No
13787,C113787,Kiran Jain,Male,1976-11-26,2024-02-23,Paid Search,Tamil Nadu,Tiruchirappalli,Standard,Yes,No
40001,C116298,Diya Mehta,Female,1970-07-25,2023-09-01,Referral,Tamil Nadu,Salem,Standard,No,Yes
16298,C116298,Diya Mehta,Female,1970-07-25,2023-09-01,Referral,Tamil Nadu,Salem,Standard,No,Yes
16441,C116441,Sneha Pillai,Male,1966-08-05,2024-08-01,Organic Search,Telangana,Warangal,Standard,Yes,No
40016,C116441,Sneha Pillai,Male,1966-08-05,2024-08-01,Organic Search,Telangana,Warangal,Standard,Yes,No
40020,C117407,Sahil Gupta,Female,1968-04-01,2024-07-07,Social Media,Delhi,New Delhi,Standard,Yes,No
17407,C117407,Sahil Gupta,Female,1968-04-01,2024-07-07,Social Media,Delhi,New Delhi,Standard,Yes,No
18948,C118948,Priya Menon,Male,2005-03-28,2023-01-27,Email,West Bengal,Kolkata,Standard,Yes,Yes
40008,C118948,Priya Menon,Male,2005-03-28,2023-01-27,Email,West Bengal,Kolkata,Standard,Yes,Yes
40017,C119463,Arun Menon,Male,1976-03-15,2023-02-03,Social Media,Kerala,Kollam,Standard,No,Yes
19463,C119463,Arun Menon,Male,1976-03-15,2023-02-03,Social Media,Kerala,Kollam,Standard,No,Yes
40027,C121261,Ananya Das,Female,2001-05-24,2022-08-16,Paid Search,Kerala,Thiruvananthapuram,Standard,No,No
21261,C121261,Ananya Das,Female,2001-05-24,2022-08-16,Paid Search,Kerala,Thiruvananthapuram,Standard,No,No
40010,C122241,Aisha Singh,Female,1974-06-10,2022-03-26,Organic Search,Bihar,Gaya,Business,Yes,No
22241,C122241,Aisha Singh,Female,1974-06-10,2022-03-26,Organic Search,Bihar,Gaya,Business,Yes,No
26173,C126173,Arjun Pillai,Female,1989-10-09,2022-01-08,Paid Search,Karnataka,Bengaluru,Premium,Yes,No
40028,C126173,Arjun Pillai,Female,1989-10-09,2022-01-08,Paid Search,Karnataka,Bengaluru,Premium,Yes,No
26283,C126283,Priya Joseph,Female,1994-11-04,2023-06-12,Organic Search,Delhi,New Delhi,Standard,Yes,No
40018,C126283,Priya Joseph,Female,1994-11-04,2023-06-12,Organic Search,Delhi,New Delhi,Standard,Yes,No
40004,C126893,Arun Mishra,Male,1974-04-24,2022-06-11,Paid Search,Uttar Pradesh,Agra,Standard,No,Yes
26893,C126893,Arun Mishra,Male,1974-04-24,2022-06-11,Paid Search,Uttar Pradesh,Agra,Standard,No,Yes
40029,C128283,Sahil Gupta,Female,2000-02-03,2024-01-13,Organic Search,Uttar Pradesh,Agra,Premium,No,Yes
28283,C128283,Sahil Gupta,Female,2000-02-03,2024-01-13,Organic Search,Uttar Pradesh,Agra,Premium,No,Yes
40002,C128505,Varun Mishra,Male,1999-10-15,2022-01-31,Organic Search,Maharashtra,Nashik,Standard,Yes,Yes
28505,C128505,Varun Mishra,Male,1999-10-15,2022-01-31,Organic Search,Maharashtra,Nashik,Standard,Yes,Yes
40007,C129591,Manu Joseph,Female,1966-06-05,2024-06-19,Organic Search,Uttar Pradesh,Varanasi,Premium,Yes,Yes
29591,C129591,Manu Joseph,Female,1966-06-05,2024-06-19,Organic Search,Uttar Pradesh,Varanasi,Premium,Yes,Yes
40022,C130866,Pooja Thomas,Male,1966-12-29,2023-06-22,Social Media,Rajasthan,Jodhpur,Standard,No,Yes
30866,C130866,Pooja Thomas,Male,1966-12-29,2023-06-22,Social Media,Rajasthan,Jodhpur,Standard,No,Yes
31067,C131067,Neha Gupta,Female,1977-03-06,2024-10-06,Organic Search,Uttar Pradesh,Agra,Standard,Yes,Yes
40009,C131067,Neha Gupta,Female,1977-03-06,2024-10-06,Organic Search,Uttar Pradesh,Agra,Standard,Yes,Yes
32823,C132823,Naveen Das,Male,1992-10-23,2023-06-26,Paid Search,Rajasthan,Udaipur,Premium,Yes,Yes
40000,C132823,Naveen Das,Male,1992-10-23,2023-06-26,Paid Search,Rajasthan,Udaipur,Premium,Yes,Yes
34089,C134089,Sneha Mishra,Female,1997-11-19,2022-03-01,Email,Kerala,Kollam,Standard,Yes,No
40026,C134089,Sneha Mishra,Female,1997-11-19,2022-03-01,Email,Kerala,Kollam,Standard,Yes,No
34436,C134436,Neha Mehta,Male,1983-12-28,2025-04-05,Social Media,Rajasthan,Jodhpur,Standard,Yes,No
40023,C134436,Neha Mehta,Male,1983-12-28,2025-04-05,Social Media,Rajasthan,Jodhpur,Standard,Yes,No
35041,C135041,Anjali Sharma,Female,1978-12-31,2023-11-29,Organic Search,Delhi,New Delhi,Standard,Yes,Yes
40014,C135041,Anjali Sharma,Female,1978-12-31,2023-11-29,Organic Search,Delhi,New Delhi,Standard,Yes,Yes
35676,C135676,Sanjay Jain,Female,2003-03-13,2022-01-08,Organic Search,Maharashtra,Nashik,Standard,No,Yes
40025,C135676,Sanjay Jain,Female,2003-03-13,2022-01-08,Organic Search,Maharashtra,Nashik,Standard,No,Yes
40019,C136216,Kavya Singh,Female,2005-03-02,2025-03-09,Organic Search,Uttar Pradesh,Agra,Premium,No,No
36216,C136216,Kavya Singh,Female,2005-03-02,2025-03-09,Organic Search,Uttar Pradesh,Agra,Premium,No,No
40005,C136572,Ananya Patel,Male,1986-02-23,2024-08-19,Organic Search,Uttar Pradesh,Lucknow,Standard,Yes,Yes
36572,C136572,Ananya Patel,Male,1986-02-23,2024-08-19,Organic Search,Uttar Pradesh,Lucknow,Standard,Yes,Yes

In [17]:
duplicate_customers.groupby("customer_id").size()

customer_id
C103510    2
C105128    2
C106689    2
C109125    2
C110919    2
C112335    2
C112701    2
C113787    2
C116298    2
C116441    2
C117407    2
C118948    2
C119463    2
C121261    2
C122241    2
C126173    2
C126283    2
C126893    2
C128283    2
C128505    2
C129591    2
C130866    2
C131067    2
C132823    2
C134089    2
C134436    2
C135041    2
C135676    2
C136216    2
C136572    2
dtype: int64

In [18]:
duplicate_customers[
    duplicate_customers["customer_id"].duplicated(keep=False)
].head(20)

,customer_id,customer_name,gender,date_of_birth,signup_date,acquisition_channel,state,city,customer_segment,email_opt_in,loyalty_member
3510,C103510,Dev Joseph,Male,1968-01-29,2025-05-12,Referral,Rajasthan,Jodhpur,Standard,Yes,Yes
40015,C103510,Dev Joseph,Male,1968-01-29,2025-05-12,Referral,Rajasthan,Jodhpur,Standard,Yes,Yes
5128,C105128,Aisha Iyer,Female,1991-01-10,2022-07-11,Paid Search,Delhi,Delhi,Standard,Yes,No
40012,C105128,Aisha Iyer,Female,1991-01-10,2022-07-11,Paid Search,Delhi,Delhi,Standard,Yes,No
6689,C106689,Pooja Thomas,Male,1987-07-23,2025-05-06,Social Media,Punjab,Amritsar,Standard,Yes,Yes
40003,C106689,Pooja Thomas,Male,1987-07-23,2025-05-06,Social Media,Punjab,Amritsar,Standard,Yes,Yes
9125,C109125,Pooja Patel,Female,1965-12-06,2022-06-14,Email,Bihar,Muzaffarpur,Standard,Yes,Yes
40013,C109125,Pooja Patel,Female,1965-12-06,2022-06-14,Email,Bihar,Muzaffarpur,Standard,Yes,Yes
10919,C110919,Arun Reddy,Female,1993-10-21,2023-12-18,Organic Search,Tamil Nadu,Madurai,Premium,No,Yes
40021,C110919,Arun Reddy,Female,1993-10-21,2023-12-18,Organic Search,Tamil Nadu,Madurai,Premium,No,Yes
40006,C112335,Rohan Thomas,Female,1965-10-29,2022-05-01,Organic Search,Kerala,Thrissur,Standard,Yes,Yes
12335,C112335,Rohan Thomas,Female,1965-10-29,2022-05-01,Organic Search,Kerala,Thrissur,Standard,Yes,Yes
12701,C112701,Nikhil Reddy,Male,1966-03-12,2022-11-17,Social Media,West Bengal,Durgapur,Standard,No,No
40024,C112701,Nikhil Reddy,Male,1966-03-12,2022-11-17,Social Media,West Bengal,Durgapur,Standard,No,No
40011,C113787,Kiran Jain,Male,1976-11-26,2024-02-23,Paid Search,Tamil Nadu,Tiruchirappalli,Standard,Yes,No
13787,C113787,Kiran Jain,Male,1976-11-26,2024-02-23,Paid Search,Tamil Nadu,Tiruchirappalli,Standard,Yes,No
40001,C116298,Diya Mehta,Female,1970-07-25,2023-09-01,Referral,Tamil Nadu,Salem,Standard,No,Yes
16298,C116298,Diya Mehta,Female,1970-07-25,2023-09-01,Referral,Tamil Nadu,Salem,Standard,No,Yes
16441,C116441,Sneha Pillai,Male,1966-08-05,2024-08-01,Organic Search,Telangana,Warangal,Standard,Yes,No
40016,C116441,Sneha Pillai,Male,1966-08-05,2024-08-01,Organic Search,Telangana,Warangal,Standard,Yes,No

In [19]:
customers.duplicated().sum()

np.int64(30)

In [20]:
customers_clean = customers.drop_duplicates().copy()

print("Original rows:", len(customers))
print("Clean rows:", len(customers_clean))
print("Rows removed:", len(customers) - len(customers_clean))

Original rows: 40030
Clean rows: 40000
Rows removed: 30

In [21]:
print(
    "Duplicate customer IDs after cleaning:",
    customers_clean["customer_id"].duplicated().sum()
)

Duplicate customer IDs after cleaning: 0

Missing Customer City

In [22]:
missing_city = customers_clean[
    customers_clean["city"].isna()
]

missing_city

,customer_id,customer_name,gender,date_of_birth,signup_date,acquisition_channel,state,city,customer_segment,email_opt_in,loyalty_member
1035,C101035,Kiran Verma,Other,1991-07-16,2023-02-06,Social Media,Tamil Nadu,NaN,Standard,No,No
3196,C103196,Meera Thomas,Male,1990-03-26,2023-07-27,Organic Search,Gujarat,NaN,Premium,Yes,No
3651,C103651,Sneha Menon,Other,1973-02-27,2024-07-17,Affiliate,Bihar,NaN,Premium,Yes,No
7084,C107084,Meera Pillai,Male,1973-10-06,2025-05-21,Email,Karnataka,NaN,Standard,No,No
7197,C107197,Sanjay Sharma,Female,2000-04-11,2025-03-13,Affiliate,Maharashtra,NaN,Premium,Yes,No
9891,C109891,Akshay Rao,Female,1970-06-17,2025-05-02,Social Media,Maharashtra,NaN,Premium,Yes,No
14024,C114024,Neha Reddy,Male,2002-09-11,2024-03-25,Email,Bihar,NaN,Standard,Yes,No
14143,C114143,Akshay Rao,Female,1992-01-02,2023-12-09,Organic Search,Telangana,NaN,Premium,Yes,Yes
17364,C117364,Dev Thomas,Male,1980-03-28,2024-06-30,Paid Search,Rajasthan,NaN,Business,Yes,Yes
25797,C125797,Akshay Kumar,Female,2002-06-26,2023-01-10,Paid Search,Madhya Pradesh,NaN,Standard,Yes,No
26419,C126419,Vivek Thomas,Female,2003-04-29,2025-02-14,Paid Search,West Bengal,NaN,Premium,Yes,No
29658,C129658,Kavya Patel,Male,1999-08-25,2025-07-10,Affiliate,Andhra Pradesh,NaN,Standard,Yes,No
32989,C132989,Diya Mishra,Male,1982-09-25,2023-12-18,Social Media,Telangana,NaN,Standard,Yes,Yes
33855,C133855,Priya Khan,Male,1999-02-05,2024-07-05,Affiliate,Rajasthan,NaN,Standard,Yes,Yes
34158,C134158,Vivek Verma,Female,2004-01-09,2024-11-17,Affiliate,Telangana,NaN,Standard,No,No
36375,C136375,Rahul Das,Female,1971-02-09,2022-01-17,Organic Search,Gujarat,NaN,Premium,Yes,No
37833,C137833,Priya Sharma,Female,1986-11-24,2023-05-07,Email,Telangana,NaN,Standard,Yes,No
38013,C138013,Priya Reddy,Female,1981-12-05,2024-04-27,Email,West Bengal,NaN,Standard,Yes,No
38522,C138522,Akshay Khan,Male,1981-09-21,2023-02-06,Social Media,Maharashtra,NaN,Premium,Yes,Yes
39537,C139537,Rohan Verma,Male,1969-09-15,2023-01-23,Paid Search,Gujarat,NaN,Standard,Yes,No

In [23]:
customers_clean["city"] = customers_clean["city"].fillna("Unknown")

In [24]:
print(
    "Missing city values:",
    customers_clean["city"].isna().sum()
)

Missing city values: 0

In [25]:
print(
    "Unknown city values:",
    (customers_clean["city"] == "Unknown").sum()
)

Unknown city values: 20

In [26]:
print("Rows:", len(customers_clean))
print("Columns:", len(customers_clean.columns))
print("Duplicate IDs:", customers_clean["customer_id"].duplicated().sum())
print("Missing values:", customers_clean.isna().sum().sum())

Rows: 40000
Columns: 11
Duplicate IDs: 0
Missing values: 0

In [27]:
missing_cost = products[
    products["cost_price"].isna()
]

missing_cost

,product_id,product_name,category,subcategory,cost_price,list_price,brand
62,P10062,Games Product 63,Toys,Games,NaN,4801.24,Brand B
145,P10145,Outdoor Product 146,Sports,Outdoor,NaN,7923.81,Private Label
170,P10170,Home Decor Product 171,Home & Kitchen,Home Decor,NaN,7585.22,Private Label
197,P10197,Men Product 198,Fashion,Men,NaN,1076.60,Private Label
536,P10536,Equipment Product 537,Sports,Equipment,NaN,522.38,Private Label
1030,P11030,Equipment Product 1031,Sports,Equipment,NaN,1013.27,Brand C
1306,P11306,Cookware Product 1307,Home & Kitchen,Cookware,NaN,279.93,Brand A
1336,P11336,Games Product 1337,Toys,Games,NaN,417.83,Private Label
1466,P11466,Snacks Product 1467,Grocery,Snacks,NaN,702.32,Brand B
2141,P12141,Packaged Foods Product 2142,Grocery,Packaged Foods,NaN,2843.39,Brand D
2274,P12274,Outdoor Product 2275,Sports,Outdoor,NaN,236.54,Brand A
2326,P12326,Cookware Product 2327,Home & Kitchen,Cookware,NaN,327.74,Private Label
2467,P12467,Staples Product 2468,Grocery,Staples,NaN,2007.70,Private Label
2478,P12478,Mobiles Product 2479,Electronics,Mobiles,NaN,57390.81,Brand D
2977,P12977,Personal Care Product 2978,Beauty,Personal Care,NaN,2285.98,Brand B

In [28]:
products[["category", "cost_price", "list_price"]].groupby(
    "category"
).agg(
    average_cost=("cost_price", "mean"),
    average_list_price=("list_price", "mean"),
    products_with_cost=("cost_price", "count")
).round(2)

                average_cost  average_list_price  products_with_cost
category
Beauty               1515.34             1900.42                 390
Books                 775.26              970.05                 371
Electronics         13876.51            17490.12                 373
Fashion              2317.41             2902.15                 383
Grocery               883.62             1102.11                 352
Home & Kitchen       3569.99             4467.97                 387
Sports               2689.76             3366.56                 358
Toys                 1808.42             2255.79                 371

In [29]:
products["cost_ratio"] = (
    products["cost_price"] / products["list_price"]
)

In [30]:
category_cost_ratio = (
    products.groupby("category")["cost_ratio"]
    .median()
)

category_cost_ratio

category
Beauty            0.797887
Books             0.797154
Electronics       0.799707
Fashion           0.802365
Grocery           0.810620
Home & Kitchen    0.797850
Sports            0.799369
Toys              0.798546
Name: cost_ratio, dtype: float64

In [31]:
products_clean = products.copy()

In [32]:
products_clean["cost_price_estimated"] = (
    products_clean["list_price"]
    * products_clean["category"].map(category_cost_ratio)
)

In [33]:
products_clean["cost_price_final"] = products_clean["cost_price"]

missing_mask = products_clean["cost_price_final"].isna()

products_clean.loc[
    missing_mask,
    "cost_price_final"
] = products_clean.loc[
    missing_mask,
    "cost_price_estimated"
]

In [34]:
products_clean["cost_price_source"] = np.where(
    products_clean["cost_price"].isna(),
    "Estimated",
    "Actual"
)

In [35]:
print("Original missing costs:", products["cost_price"].isna().sum())

print(
    "Missing final costs:",
    products_clean["cost_price_final"].isna().sum()
)

print(
    "Estimated costs:",
    (products_clean["cost_price_source"] == "Estimated").sum()
)

Original missing costs: 15
Missing final costs: 0
Estimated costs: 15

In [36]:
duplicate_orders = orders[
    orders["order_id"].duplicated(keep=False)
].sort_values("order_id")

duplicate_orders

,order_id,customer_id,order_date,payment_method,order_status,shipping_type
1007,O1001007,C101656,2023-11-07,UPI,Completed,Standard
180000,O1001007,C101656,2023-11-07,UPI,Completed,Standard
14823,O1014823,C117116,2025-10-11,Wallet,Completed,Standard
180009,O1014823,C117116,2025-10-11,Wallet,Completed,Standard
16663,O1016663,C106438,2024-11-15,UPI,Completed,Standard
180005,O1016663,C106438,2024-11-15,UPI,Completed,Standard
33221,O1033221,C101192,2024-01-06,COD,Completed,Standard
180008,O1033221,C101192,2024-01-06,COD,Completed,Standard
35994,O1035994,C130237,2024-10-28,COD,Completed,Standard
180002,O1035994,C130237,2024-10-28,COD,Completed,Standard
180011,O1059035,C122483,2024-11-21,UPI,Completed,Standard
59035,O1059035,C122483,2024-11-21,UPI,Completed,Standard
180004,O1062653,C123074,2023-01-05,Debit Card,Completed,Standard
62653,O1062653,C123074,2023-01-05,Debit Card,Completed,Standard
180001,O1093344,C133321,2024-02-04,UPI,Completed,Standard
93344,O1093344,C133321,2024-02-04,UPI,Completed,Standard
180010,O1108096,C106712,2025-10-29,Credit Card,Completed,Standard
108096,O1108096,C106712,2025-10-29,Credit Card,Completed,Standard
128604,O1128604,C122996,2023-12-21,COD,Completed,Standard
180006,O1128604,C122996,2023-12-21,COD,Completed,Standard
180007,O1163086,C130661,2024-07-11,UPI,Completed,Standard
163086,O1163086,C130661,2024-07-11,UPI,Completed,Standard
180003,O1163853,C116750,2023-01-21,COD,Completed,Standard
163853,O1163853,C116750,2023-01-21,COD,Completed,Standard

In [37]:
duplicate_orders.duplicated().sum()

np.int64(12)

In [38]:
orders_clean = orders.drop_duplicates().copy()

print("Original rows:", len(orders))
print("Clean rows:", len(orders_clean))
print("Rows removed:", len(orders) - len(orders_clean))

Original rows: 180012
Clean rows: 180000
Rows removed: 12

In [39]:
print(
    "Duplicate order IDs after cleaning:",
    orders_clean["order_id"].duplicated().sum()
)

Duplicate order IDs after cleaning: 0

In [40]:
invalid_items = order_items[
    order_items["quantity"] <= 0
].copy()

print("Invalid order-item records:", len(invalid_items))

invalid_items

Invalid order-item records: 40

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,gross_amount
13621,OI2013621,O1007205,P10909,-1,1216.04,10.81,2432.08
21058,OI2021058,O1011122,P10688,-1,1238.46,12.97,1238.46
23334,OI2023334,O1012332,P11346,-1,5551.29,13.57,5551.29
28251,OI2028251,O1014901,P11301,-1,8411.39,3.94,8411.39
30640,OI2030640,O1016180,P11335,0,418.87,14.08,418.87
46745,OI2046745,O1024755,P12086,-1,1454.70,5.40,1454.70
54836,OI2054836,O1029028,P11862,0,4638.11,11.55,4638.11
58350,OI2058350,O1030904,P11792,-1,6295.83,6.99,6295.83
64524,OI2064524,O1034167,P11748,0,9995.95,11.10,9995.95
67413,OI2067413,O1035701,P10976,-1,1818.50,6.07,1818.50
69951,OI2069951,O1037052,P11082,0,970.66,14.51,970.66
71900,OI2071900,O1038125,P10286,0,1883.29,8.12,1883.29
99606,OI2099606,O1052826,P12973,0,1546.90,7.13,1546.90
105342,OI2105342,O1055884,P10299,0,4162.54,11.60,4162.54
115030,OI2115030,O1060967,P11587,0,203.70,4.64,203.70
132023,OI2132023,O1069971,P11140,0,640.23,3.58,1280.46
134716,OI2134716,O1071393,P10168,0,1368.14,19.64,1368.14
146203,OI2146203,O1077478,P11532,-1,1008.48,3.40,1008.48
155546,OI2155546,O1082474,P10299,0,4365.84,7.28,4365.84
155739,OI2155739,O1082578,P12991,0,5710.70,7.14,5710.70
157057,OI2157057,O1083287,P10658,-1,5725.11,8.35,11450.22
173958,OI2173958,O1092290,P11388,0,2918.58,5.03,2918.58
181484,OI2181484,O1096247,P11525,-1,2661.63,4.94,2661.63
203207,OI2203207,O1107720,P10940,0,2177.53,7.04,2177.53
205342,OI2205342,O1108873,P10418,0,1220.44,2.32,1220.44
209524,OI2209524,O1111098,P12042,-1,901.17,27.18,901.17
214321,OI2214321,O1113653,P11783,0,554.26,10.68,554.26
215333,OI2215333,O1114172,P11499,-1,15544.67,22.85,31089.34
219530,OI2219530,O1116439,P10058,-1,1733.27,5.94,3466.54
228797,OI2228797,O1121336,P12651,0,96.11,2.72,96.11
244592,OI2244592,O1129781,P10438,-1,249.78,13.37,249.78
251139,OI2251139,O1133330,P12806,0,9439.59,0.29,18879.18
252120,OI2252120,O1133817,P11609,-1,145.78,8.66,145.78
261080,OI2261080,O1138563,P10344,-1,3506.84,14.88,3506.84
282680,OI2282680,O1150027,P11796,-1,1117.93,4.45,1117.93
292130,OI2292130,O1155096,P10366,-1,705.55,8.59,705.55
310031,OI2310031,O1164627,P10514,-1,541.69,9.86,541.69
317751,OI2317751,O1168730,P10398,0,173.10,24.43,173.10
320536,OI2320536,O1170194,P12230,0,2713.74,1.68,2713.74
323001,OI2323001,O1171492,P12335,-1,1347.84,6.75,1347.84

In [41]:
quarantine_items = invalid_items.copy()

quarantine_items["rejection_reason"] = "Invalid quantity (<= 0)"

print("Records quarantined:", len(quarantine_items))

Records quarantined: 40

In [42]:
order_items_clean = order_items[
    order_items["quantity"] > 0
].copy()

print("Original rows:", len(order_items))
print("Clean rows:", len(order_items_clean))
print("Rows removed:", len(order_items) - len(order_items_clean))

Original rows: 339053
Clean rows: 339013
Rows removed: 40

In [43]:
print(
    "Invalid quantities remaining:",
    (order_items_clean["quantity"] <= 0).sum()
)

Invalid quantities remaining: 0

In [44]:
invalid_items = order_items[
    order_items["quantity"] <= 0
].copy()

print("Invalid order-item records:", len(invalid_items))

invalid_items

Invalid order-item records: 40

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,gross_amount
13621,OI2013621,O1007205,P10909,-1,1216.04,10.81,2432.08
21058,OI2021058,O1011122,P10688,-1,1238.46,12.97,1238.46
23334,OI2023334,O1012332,P11346,-1,5551.29,13.57,5551.29
28251,OI2028251,O1014901,P11301,-1,8411.39,3.94,8411.39
30640,OI2030640,O1016180,P11335,0,418.87,14.08,418.87
46745,OI2046745,O1024755,P12086,-1,1454.70,5.40,1454.70
54836,OI2054836,O1029028,P11862,0,4638.11,11.55,4638.11
58350,OI2058350,O1030904,P11792,-1,6295.83,6.99,6295.83
64524,OI2064524,O1034167,P11748,0,9995.95,11.10,9995.95
67413,OI2067413,O1035701,P10976,-1,1818.50,6.07,1818.50
69951,OI2069951,O1037052,P11082,0,970.66,14.51,970.66
71900,OI2071900,O1038125,P10286,0,1883.29,8.12,1883.29
99606,OI2099606,O1052826,P12973,0,1546.90,7.13,1546.90
105342,OI2105342,O1055884,P10299,0,4162.54,11.60,4162.54
115030,OI2115030,O1060967,P11587,0,203.70,4.64,203.70
132023,OI2132023,O1069971,P11140,0,640.23,3.58,1280.46
134716,OI2134716,O1071393,P10168,0,1368.14,19.64,1368.14
146203,OI2146203,O1077478,P11532,-1,1008.48,3.40,1008.48
155546,OI2155546,O1082474,P10299,0,4365.84,7.28,4365.84
155739,OI2155739,O1082578,P12991,0,5710.70,7.14,5710.70
157057,OI2157057,O1083287,P10658,-1,5725.11,8.35,11450.22
173958,OI2173958,O1092290,P11388,0,2918.58,5.03,2918.58
181484,OI2181484,O1096247,P11525,-1,2661.63,4.94,2661.63
203207,OI2203207,O1107720,P10940,0,2177.53,7.04,2177.53
205342,OI2205342,O1108873,P10418,0,1220.44,2.32,1220.44
209524,OI2209524,O1111098,P12042,-1,901.17,27.18,901.17
214321,OI2214321,O1113653,P11783,0,554.26,10.68,554.26
215333,OI2215333,O1114172,P11499,-1,15544.67,22.85,31089.34
219530,OI2219530,O1116439,P10058,-1,1733.27,5.94,3466.54
228797,OI2228797,O1121336,P12651,0,96.11,2.72,96.11
244592,OI2244592,O1129781,P10438,-1,249.78,13.37,249.78
251139,OI2251139,O1133330,P12806,0,9439.59,0.29,18879.18
252120,OI2252120,O1133817,P11609,-1,145.78,8.66,145.78
261080,OI2261080,O1138563,P10344,-1,3506.84,14.88,3506.84
282680,OI2282680,O1150027,P11796,-1,1117.93,4.45,1117.93
292130,OI2292130,O1155096,P10366,-1,705.55,8.59,705.55
310031,OI2310031,O1164627,P10514,-1,541.69,9.86,541.69
317751,OI2317751,O1168730,P10398,0,173.10,24.43,173.10
320536,OI2320536,O1170194,P12230,0,2713.74,1.68,2713.74
323001,OI2323001,O1171492,P12335,-1,1347.84,6.75,1347.84

In [45]:
quarantine_items = invalid_items.copy()

quarantine_items["rejection_reason"] = "Invalid quantity (<= 0)"

print("Records quarantined:", len(quarantine_items))

Records quarantined: 40

In [46]:
order_items_clean = order_items[
    order_items["quantity"] > 0
].copy()

print("Original rows:", len(order_items))
print("Clean rows:", len(order_items_clean))
print("Invalid rows removed:", len(order_items) - len(order_items_clean))

Original rows: 339053
Clean rows: 339013
Invalid rows removed: 40

In [47]:
invalid_after_cleaning = (
    order_items_clean["quantity"] <= 0
).sum()

print("Invalid quantities after cleaning:", invalid_after_cleaning)

Invalid quantities after cleaning: 0

In [48]:
missing_payment = payments[
    payments["payment_method"].isna()
].copy()

print("Missing payment methods:", len(missing_payment))

missing_payment

Missing payment methods: 25

        payment_id  order_id payment_date payment_method payment_status
4253    PAY3004253  O1004253   2024-03-17            NaN           Paid
9362    PAY3009362  O1009362   2023-01-01            NaN           Paid
9692    PAY3009692  O1009692   2023-06-22            NaN       Refunded
20237   PAY3020237  O1020237   2024-05-28            NaN           Paid
21324   PAY3021324  O1021324   2023-07-12            NaN           Paid
35081   PAY3035081  O1035081   2024-11-07            NaN           Paid
45411   PAY3045411  O1045411   2025-06-12            NaN           Paid
57744   PAY3057744  O1057744   2025-08-17            NaN           Paid
67745   PAY3067745  O1067745   2024-01-10            NaN           Paid
77215   PAY3077215  O1077215   2025-06-11            NaN           Paid
78424   PAY3078424  O1078424   2023-01-03            NaN           Paid
81425   PAY3081425  O1081425   2023-10-05            NaN           Paid
105215  PAY3105215  O1105215   2025-10-20            NaN       Refunded
108334  PAY3108334  O1108334   2024-11-22            NaN           Paid
112565  PAY3112565  O1112565   2025-10-08            NaN           Paid
116320  PAY3116320  O1116320   2024-04-18            NaN           Paid
117116  PAY3117116  O1117116   2024-04-29            NaN           Paid
123207  PAY3123207  O1123207   2025-09-30            NaN           Paid
143300  PAY3143300  O1143300   2024-01-16            NaN           Paid
148820  PAY3148820  O1148820   2023-08-03            NaN           Paid
149754  PAY3149754  O1149754   2023-04-25            NaN           Paid
151386  PAY3151386  O1151386   2024-05-13            NaN           Paid
151752  PAY3151752  O1151752   2024-02-02            NaN           Paid
157065  PAY3157065  O1157065   2023-03-23            NaN           Paid
173344  PAY3173344  O1173344   2025-03-25            NaN           Paid

In [49]:
order_payment_map = orders_clean.set_index(
    "order_id"
)["payment_method"]

payments_clean = payments.copy()

payments_clean["payment_method_recovered"] = (
    payments_clean["order_id"].map(order_payment_map)
)

payments_clean.loc[
    payments_clean["payment_method"].isna(),
    ["order_id", "payment_method", "payment_method_recovered"]
]

        order_id payment_method payment_method_recovered
4253    O1004253            NaN                      UPI
9362    O1009362            NaN               Debit Card
9692    O1009692            NaN                      UPI
20237   O1020237            NaN                      COD
21324   O1021324            NaN              Net Banking
35081   O1035081            NaN                      UPI
45411   O1045411            NaN               Debit Card
57744   O1057744            NaN                      UPI
67745   O1067745            NaN              Credit Card
77215   O1077215            NaN              Net Banking
78424   O1078424            NaN              Credit Card
81425   O1081425            NaN                      UPI
105215  O1105215            NaN                      UPI
108334  O1108334            NaN                      UPI
112565  O1112565            NaN                      UPI
116320  O1116320            NaN                      UPI
117116  O1117116            NaN                      UPI
123207  O1123207            NaN              Net Banking
143300  O1143300            NaN                      UPI
148820  O1148820            NaN                   Wallet
149754  O1149754            NaN                      UPI
151386  O1151386            NaN                      UPI
151752  O1151752            NaN              Credit Card
157065  O1157065            NaN                      UPI
173344  O1173344            NaN                      UPI

In [50]:
recovery_mask = payments_clean["payment_method"].isna()

payments_clean.loc[
    recovery_mask,
    "payment_method"
] = payments_clean.loc[
    recovery_mask,
    "payment_method_recovered"
]

payments_clean["payment_method_source"] = np.where(
    recovery_mask,
    "Recovered from Orders",
    "Original"
)

print(
    "Recovered payment methods:",
    recovery_mask.sum()
)

print(
    "Remaining missing payment methods:",
    payments_clean["payment_method"].isna().sum()
)

Recovered payment methods: 25
Remaining missing payment methods: 0

In [51]:
payments_clean = payments_clean.drop(
    columns=["payment_method_recovered"]
)

payments_clean.head()

,payment_id,order_id,payment_date,payment_method,payment_status,payment_method_source
0,PAY3000000,O1000000,2023-03-16,Credit Card,Paid,Original
1,PAY3000001,O1000001,2024-01-26,COD,Paid,Original
2,PAY3000002,O1000002,2024-07-15,Debit Card,Paid,Original
3,PAY3000003,O1000003,2024-03-31,COD,Paid,Original
4,PAY3000004,O1000004,2025-01-16,Wallet,Paid,Original

In [52]:
returns_clean = returns.copy()
marketing_clean = marketing.copy()

print("Returns rows:", len(returns_clean))
print("Marketing rows:", len(marketing_clean))

Returns rows: 18000
Marketing rows: 180

In [53]:
customers_clean["date_of_birth"] = pd.to_datetime(
    customers_clean["date_of_birth"]
)

customers_clean["signup_date"] = pd.to_datetime(
    customers_clean["signup_date"]
)

orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"]
)

payments_clean["payment_date"] = pd.to_datetime(
    payments_clean["payment_date"]
)

returns_clean["return_date"] = pd.to_datetime(
    returns_clean["return_date"]
)

marketing_clean["campaign_date"] = pd.to_datetime(
    marketing_clean["campaign_date"]
)

print("Date conversion completed.")

Date conversion completed.

In [54]:
clean_datasets = {
    "customers": customers_clean,
    "products": products_clean,
    "orders": orders_clean,
    "order_items": order_items_clean,
    "payments": payments_clean,
    "returns": returns_clean,
    "marketing": marketing_clean
}

for name, df in clean_datasets.items():
    print(f"{name:15} : {len(df):,} rows")

customers       : 40,000 rows
products        : 3,000 rows
orders          : 180,000 rows
order_items     : 339,013 rows
payments        : 180,000 rows
returns         : 18,000 rows
marketing       : 180 rows

In [55]:
key_checks_clean = {
    "customers": ("customer_id", customers_clean),
    "products": ("product_id", products_clean),
    "orders": ("order_id", orders_clean),
    "order_items": ("order_item_id", order_items_clean),
    "payments": ("payment_id", payments_clean),
    "returns": ("return_id", returns_clean),
    "marketing": ("campaign_id", marketing_clean)
}

for name, (key, df) in key_checks_clean.items():
    duplicates = df[key].duplicated().sum()

    print(
        f"{name:15} | "
        f"{key:15} | "
        f"duplicate keys: {duplicates}"
    )

customers       | customer_id     | duplicate keys: 0
products        | product_id      | duplicate keys: 0
orders          | order_id        | duplicate keys: 0
order_items     | order_item_id   | duplicate keys: 0
payments        | payment_id      | duplicate keys: 0
returns         | return_id       | duplicate keys: 0
marketing       | campaign_id     | duplicate keys: 0

In [56]:
for name, df in clean_datasets.items():

    missing = df.isna().sum().sum()

    print(
        f"{name:15} | "
        f"missing values: {missing}"
    )

customers       | missing values: 0
products        | missing values: 30
orders          | missing values: 0
order_items     | missing values: 0
payments        | missing values: 0
returns         | missing values: 0
marketing       | missing values: 0

In [57]:
customers_clean.to_csv(
    CLEAN_PATH / "customers_clean.csv",
    index=False
)

products_clean.to_csv(
    CLEAN_PATH / "products_clean.csv",
    index=False
)

orders_clean.to_csv(
    CLEAN_PATH / "orders_clean.csv",
    index=False
)

order_items_clean.to_csv(
    CLEAN_PATH / "order_items_clean.csv",
    index=False
)

payments_clean.to_csv(
    CLEAN_PATH / "payments_clean.csv",
    index=False
)

returns_clean.to_csv(
    CLEAN_PATH / "returns_clean.csv",
    index=False
)

marketing_clean.to_csv(
    CLEAN_PATH / "marketing_campaigns_clean.csv",
    index=False
)

print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.

In [58]:
quarantine_items.to_csv(
    CLEAN_PATH / "quarantine_order_items.csv",
    index=False
)

print(
    "Quarantine records saved:",
    len(quarantine_items)
)

Quarantine records saved: 40

In [59]:
cleaning_summary = pd.DataFrame([
    {
        "dataset": "Customers",
        "original_rows": len(customers),
        "clean_rows": len(customers_clean),
        "records_removed": len(customers) - len(customers_clean)
    },
    {
        "dataset": "Products",
        "original_rows": len(products),
        "clean_rows": len(products_clean),
        "records_removed": len(products) - len(products_clean)
    },
    {
        "dataset": "Orders",
        "original_rows": len(orders),
        "clean_rows": len(orders_clean),
        "records_removed": len(orders) - len(orders_clean)
    },
    {
        "dataset": "Order Items",
        "original_rows": len(order_items),
        "clean_rows": len(order_items_clean),
        "records_removed": len(order_items) - len(order_items_clean)
    },
    {
        "dataset": "Payments",
        "original_rows": len(payments),
        "clean_rows": len(payments_clean),
        "records_removed": len(payments) - len(payments_clean)
    },
    {
        "dataset": "Returns",
        "original_rows": len(returns),
        "clean_rows": len(returns_clean),
        "records_removed": len(returns) - len(returns_clean)
    },
    {
        "dataset": "Marketing",
        "original_rows": len(marketing),
        "clean_rows": len(marketing_clean),
        "records_removed": len(marketing) - len(marketing_clean)
    }
])

cleaning_summary

       dataset  original_rows  clean_rows  records_removed
0    Customers          40030       40000               30
1     Products           3000        3000                0
2       Orders         180012      180000               12
3  Order Items         339053      339013               40
4     Payments         180000      180000                0
5      Returns          18000       18000                0
6    Marketing            180         180                0

In [60]:
cleaning_summary.to_csv(
    CLEAN_PATH / "Cleaning_Summary.csv",
    index=False
)

print("Cleaning summary saved.")

Cleaning summary saved.

In [61]:
missing_product_ids = [
    "P10062",
    "P10145",
    "P10170",
    "P10197",
    "P10536",
    "P11030",
    "P11306",
    "P11336",
    "P11466",
    "P12141",
    "P12274",
    "P12326",
    "P12467",
    "P12478",
    "P12977"
]

missing_products = products_clean[
    products_clean["product_id"].isin(missing_product_ids)
].copy()

print("Missing products found:", len(missing_products))

missing_products

Missing products found: 15

,product_id,product_name,category,subcategory,cost_price,list_price,brand,cost_ratio,cost_price_estimated,cost_price_final,cost_price_source
62,P10062,Games Product 63,Toys,Games,NaN,4801.24,Brand B,NaN,3834.009451,3834.009451,Estimated
145,P10145,Outdoor Product 146,Sports,Outdoor,NaN,7923.81,Private Label,NaN,6334.047056,6334.047056,Estimated
170,P10170,Home Decor Product 171,Home & Kitchen,Home Decor,NaN,7585.22,Private Label,NaN,6051.870988,6051.870988,Estimated
197,P10197,Men Product 198,Fashion,Men,NaN,1076.60,Private Label,NaN,863.826345,863.826345,Estimated
536,P10536,Equipment Product 537,Sports,Equipment,NaN,522.38,Private Label,NaN,417.574311,417.574311,Estimated
1030,P11030,Equipment Product 1031,Sports,Equipment,NaN,1013.27,Brand C,NaN,809.976496,809.976496,Estimated
1306,P11306,Cookware Product 1307,Home & Kitchen,Cookware,NaN,279.93,Brand A,NaN,223.342269,223.342269,Estimated
1336,P11336,Games Product 1337,Toys,Games,NaN,417.83,Private Label,NaN,333.656341,333.656341,Estimated
1466,P11466,Snacks Product 1467,Grocery,Snacks,NaN,702.32,Brand B,NaN,569.314351,569.314351,Estimated
2141,P12141,Packaged Foods Product 2142,Grocery,Packaged Foods,NaN,2843.39,Brand D,NaN,2304.907638,2304.907638,Estimated
2274,P12274,Outdoor Product 2275,Sports,Outdoor,NaN,236.54,Brand A,NaN,189.082713,189.082713,Estimated
2326,P12326,Cookware Product 2327,Home & Kitchen,Cookware,NaN,327.74,Private Label,NaN,261.487498,261.487498,Estimated
2467,P12467,Staples Product 2468,Grocery,Staples,NaN,2007.70,Private Label,NaN,1627.480952,1627.480952,Estimated
2478,P12478,Mobiles Product 2479,Electronics,Mobiles,NaN,57390.81,Brand D,NaN,45895.815003,45895.815003,Estimated
2977,P12977,Personal Care Product 2978,Beauty,Personal Care,NaN,2285.98,Brand B,NaN,1823.954467,1823.954467,Estimated

In [62]:
missing_products_path = CLEAN_PATH / "missing_products.csv"

missing_products.to_csv(
    missing_products_path,
    index=False
)

print("Saved:", missing_products_path.resolve())
print("Rows saved:", len(missing_products))

Saved: C:\Users\USER\OneDrive\Desktop\ShopSphere-Ecommerce-Analytics\04_Python_ETL\cleaned_data\missing_products.csv
Rows saved: 15